# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20161118_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Hospital', verbose_name='Hospital'),
            preserve_default=False,
        ),
    ]
