# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_answer_hospital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordering', 'created'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['ordering', 'created'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='subquestion',
            options={'ordering': ['ordering', 'created'], 'verbose_name': 'Subquestion', 'verbose_name_plural': 'Subquestions'},
        ),
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='question',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
        ),
    ]
