# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20161118_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['participant', 'hospital', 'subquestion'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
    ]
