# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_subquestion_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='instruction',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Instruction'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='kind',
            field=models.CharField(choices=[('int', 'Integer'), ('text', 'Text'), ('ltext', 'Long text')], default='text', max_length=5, verbose_name='Kind of answer'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='End text'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='submit_text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Submit text'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='welcome_text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Welcome text'),
        ),
    ]
