# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20161120_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='identifier',
            field=models.CharField(blank=True, help_text='The internal identifier used to connect foundation database', max_length=15, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='nationalhealtfund',
            name='identifier',
            field=models.CharField(blank=True, help_text='The internal identifier used to connect foundation database', max_length=15, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='health_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.NationalHealtFund', verbose_name='National Healt Fund'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='participants',
            field=models.ManyToManyField(through='survey.Participant', to='survey.NationalHealtFund', verbose_name='Participants'),
        ),
    ]
