# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 01:51
from __future__ import unicode_literals

from django.db import migrations, models


def update_answer_count(apps, schema_editor):
    Participant = apps.get_model("survey", "Participant")

    for p in (Participant.objects.
              annotate(db_answer_count=models.Count('answer', distinct=True)).
              all()):
        p.answer_count = p.db_answer_count
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20161121_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='answer_count',
            field=models.IntegerField(default=0, verbose_name='Answer count'),
        ),
        migrations.RunPython(update_answer_count)
    ]
