# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 02:16
from __future__ import unicode_literals

from django.db import migrations, models


def update_answer_count(apps, schema_editor):
    Survey = apps.get_model("survey", "Survey")

    for p in (Survey.objects.
              annotate(db_subquestion_count=models.Count('category__question__subquestion',
                                                         distinct=True)).
              all()):
        p.subquestion_count = p.db_subquestion_count
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_survey_subquestion_count'),
    ]

    operations = [
            migrations.RunPython(update_answer_count)

    ]
