# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20161127_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='style',
            field=models.IntegerField(choices=[(0, 'Total view'), (1, 'Hospital view'), (1, 'Question view')], default=1),
        ),
    ]
