# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_survey_style'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='participant',
            index_together=set([('id', 'password')]),
        ),
    ]
