# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20161128_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='style',
            field=models.IntegerField(choices=[(0, 'Total view'), (1, 'Hospital view'), (2, 'Question view')], default=2),
        ),
    ]
