# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20161128_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='print_style',
            field=models.IntegerField(choices=[(0, 'Print per hospital'), (1, 'Print per question')], default=1),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='kind',
            field=models.CharField(choices=[('int', 'Integer'), ('text', 'Text'), ('ltext', 'Long text'), ('vint', 'Value or text')], default='text', max_length=5, verbose_name='Kind of answer'),
        ),
    ]
