# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_auto_20161130_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='voivodeship',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Voivodeship'),
        ),
    ]
