# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_auto_20161201_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='accept_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accept on'),
        ),
    ]
